### ISSUE TITLE
Invalid ISO error

### ISSUE THREAD

**Issue by leatherbacks** [O-Hahn/node-red-contrib-camerapi#18]
I am getting the following error after installing the latest update:

Traceback (most recent call last):
  File "/root/.node-red/node_modules/node-red-contrib-camerapi/lib/python/get_photo.py", line 64, in <module>
    camera.iso = iso
  File "/usr/lib/python2.7/dist-packages/picamera/camera.py", line 2778, in _set_iso
    raise PiCameraValueError("Invalid iso value: %s" % value)
picamera.exc.PiCameraValueError: Invalid iso value: 400

**Comment by leatherbacks** [comment]
was fixed by upgrading to more recent node.js version
